TRAINING_SAMPLES = [
    ("uber ride to office", "Travel"),
    ("petrol refill shell", "Travel"),
    ("metro recharge", "Travel"),
    ("flight ticket to mumbai", "Travel"),
    ("swiggy dinner order", "Food"),
    ("zomato lunch combo", "Food"),
    ("groceries from bigbasket", "Groceries"),
    ("vegetables and fruits market", "Groceries"),
    ("electricity bill payment", "Bills"),
    ("internet broadband recharge", "Bills"),
    ("water bill online", "Bills"),
    ("netflix subscription", "Subscriptions"),
    ("spotify premium renewal", "Subscriptions"),
    ("amazon prime membership", "Subscriptions"),
    ("movie tickets with friends", "Entertainment"),
    ("weekend cafe brunch", "Entertainment"),
    ("doctor consultation", "Healthcare"),
    ("medical store pharmacy", "Healthcare"),
    ("gym membership", "Health & Fitness"),
    ("yoga class fee", "Health & Fitness"),
    ("monthly rent transfer", "Housing"),
    ("home maintenance repair", "Housing"),
    ("shopping at myntra", "Shopping"),
    ("new shoes purchase", "Shopping"),
    ("school tuition fee", "Education"),
    ("online course subscription", "Education"),
    ("salary credited", "Income"),
    ("freelance project payment", "Income"),
    ("charity donation", "Giving"),
    ("bank charge and fees", "Fees"),
]
